### PR TITLE
Better ARM recognition for compilers like arm-cortexa8-linux-gnueabihf

### PR DESCRIPTION
**Pull request by DoomHammer**

### CODE REVIEW

**Comment by DoomHammer** [comment]
@stathisv @SimonChisholm could you please review the PR?

**Comment by DoomHammer** [comment]
I might be missing something. There is a mutual exclusion between QNAP and `armel`/`armhf`. How should it be possible to generate QNAP with amrhf this way?

**Comment by stathisv** [comment]
Your patch is not wrong. I am just trying to catch a user error earlier in the build process.

Suppose someone calls the Makefile with platform=Qnap and CROSS_COMPILE set to point to an 'armhf' compiler, which is an error, because the QNAP x19 variant needs an ARM soft float build.

I have not tried it but by looking at the code I think with your patch the build will succeed and produce a set of binaries that however are unusable for that QNAP platform.

With the change that I am suggesting detected_home_architecture would be set to 'armhf' instead of 'x19'. That would cause the build to fail further down, definitely in the bundle_binaries.py script, because Qnap/armhf is not a supported combination.
I think in this case we want the build to fail instead of unintentionally producing unusable binaries.

**Comment by DoomHammer** [comment]
How about the current approach?

**Comment by stathisv** [comment]
The patch has now been merged locally. It should be on Github later tonight. Thank you.

**Pull request closed without merging**
